export type {AppProps} from './AppProps';
export type {Technology} from './Technology';
export type {Contact} from './Contact';
export type {Headline} from './Headline';
export type {HomeProps} from './HomeProps';
export type {MenuItem} from './MenuItem';
export type {StringArray} from './StringArray';
export type {Job} from './Job';
export type {Project} from './Project';
