name: Deploy to BRIANADERERCOM Main

on:
  push:
    branches:
      - main  # Set this to your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      BACKEND_LOCATION: 'https://admin.brianaderer.com'
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies and Build Next.js app
        run: |
          npm install
          npm run build

      - name: Rsync All Files Except .env.local
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete --exclude='.env'
          path: ./
          remote_path: ~/brianaderer/
          remote_host: 3.15.144.253
          remote_port: 22
          remote_user: brianaderer_ssh
          remote_key: ${{ secrets.SSH_KEY }}

#      - name: Restart Application and Clear Cache
#        uses: appleboy/ssh-action@master
#        with:
#          host: 3.15.144.253
#          username: badererSudo
#          key: ${{ secrets.STAGING_SSH }}
#          script: |
#            rm -rf /var/cache/nginx/*
#            pm2 startOrReload ~/files/ecosystem.config.js --watch

